import {
  readdirSync,
  statSync,
  readFileSync,
  existsSync,
  mkdirSync,
  writeFileSync,
} from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { format } from "prettier";

const __dirname = dirname(fileURLToPath(import.meta.url));

const generatedContractComment = `
/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */`;

function getDirectories(path) {
  if (!existsSync(path)) {
    return [];
  }

  return readdirSync(path).filter(function (file) {
    return statSync(join(path, file)).isDirectory();
  });
}

function getFiles(path) {
  return readdirSync(path).filter(function (file) {
    return statSync(join(path, file)).isFile();
  });
}

function parseTransactionAndReceiptRun(filePath) {
  try {
    const content = readFileSync(filePath, "utf8");
    const broadcastData = JSON.parse(content);
    return {
      transactions: broadcastData.transactions || [],
      receipts: broadcastData.receipts || [],
    };
  } catch (error) {
    console.warn(`Warning: Could not parse ${filePath}:`, error.message);
    return [];
  }
}

function getDeploymentHistory(broadcastPath) {
  const files = getFiles(broadcastPath);
  const deploymentHistory = new Map();

  // Sort files to process them in chronological order
  const runFiles = files
    .filter(
      (file) =>
        file.startsWith("run-") &&
        file.endsWith(".json") &&
        !file.includes("run-latest")
    )
    .sort((a, b) => {
      // Extract run numbers and compare them
      const runA = parseInt(a.match(/run-(\d+)/)?.[1] || "0");
      const runB = parseInt(b.match(/run-(\d+)/)?.[1] || "0");
      return runA - runB;
    });

  for (const file of runFiles) {
    const { transactions, receipts } = parseTransactionAndReceiptRun(
      join(broadcastPath, file)
    );

    for (const tx of transactions) {
      if (tx.transactionType === "CREATE" || tx.transactionType === "CREATE2") {
        // Store or update contract deployment info
        deploymentHistory.set(tx.contractAddress, {
          contractName: tx.contractName,
          address: tx.contractAddress,
          deploymentFile: file,
          transaction: tx,
          receipt: receipts.find((r) => r.transactionHash === tx.hash),
        });
      }
    }
  }

  return Array.from(deploymentHistory.values());
}

function getArtifactOfContract(contractName) {
  const current_path_to_artifacts = join(
    __dirname,
    "..",
    `out/${contractName}.sol`
  );

  if (!existsSync(current_path_to_artifacts)) return null;

  const artifactJson = JSON.parse(
    readFileSync(`${current_path_to_artifacts}/${contractName}.json`)
  );

  return artifactJson;
}

function getInheritedFromContracts(artifact) {
  let inheritedFromContracts = [];
  if (artifact?.ast) {
    for (const astNode of artifact.ast.nodes) {
      if (astNode.nodeType == "ContractDefinition") {
        if (astNode.baseContracts.length > 0) {
          inheritedFromContracts = astNode.baseContracts.map(
            ({ baseName }) => baseName.name
          );
        }
      }
    }
  }
  return inheritedFromContracts;
}

function getInheritedFunctions(mainArtifact) {
  const inheritedFromContracts = getInheritedFromContracts(mainArtifact);
  const inheritedFunctions = {};
  for (const inheritanceContractName of inheritedFromContracts) {
    const artifact = getArtifactOfContract(inheritanceContractName);
    if (artifact) {
      const {
        abi,
        ast: { absolutePath },
      } = artifact;
      for (const abiEntry of abi) {
        if (abiEntry.type == "function") {
          inheritedFunctions[abiEntry.name] = absolutePath;
        }
      }
    }
  }
  return inheritedFunctions;
}

function processAllDeployments(broadcastPath) {
  const scriptFolders = getDirectories(broadcastPath);
  const allDeployments = new Map();

  scriptFolders.forEach((scriptFolder) => {
    const scriptPath = join(broadcastPath, scriptFolder);
    const chainFolders = getDirectories(scriptPath);

    chainFolders.forEach((chainId) => {
      const chainPath = join(scriptPath, chainId);
      const deploymentHistory = getDeploymentHistory(chainPath);

      deploymentHistory.forEach((deployment) => {
        const timestamp = parseInt(
          deployment.deploymentFile.match(/run-(\d+)/)?.[1] || "0"
        );
        const key = `${chainId}-${deployment.contractName}`;

        // Only update if this deployment is newer
        if (
          !allDeployments.has(key) ||
          timestamp > allDeployments.get(key).timestamp
        ) {
          allDeployments.set(key, {
            ...deployment,
            timestamp,
            chainId,
            deploymentScript: scriptFolder,
            deployedOnBlock: deployment?.receipt?.blockNumber,
          });
        }
      });
    });
  });

  const allContracts = {};
  const deployers = {};

  allDeployments.forEach((deployment) => {
    const { chainId, contractName } = deployment;

    // Capture deployer address from first CREATE transaction per chain
    if (!deployers[chainId]) {
      const from = deployment.transaction?.transaction?.from;
      if (from) deployers[chainId] = from;
    }

    const artifact = getArtifactOfContract(contractName);

    if (artifact) {
      if (!allContracts[chainId]) {
        allContracts[chainId] = {};
      }

      allContracts[chainId][contractName] = {
        address: deployment.address,
        abi: artifact.abi,
        inheritedFunctions: getInheritedFunctions(artifact),
        deploymentFile: deployment.deploymentFile,
        deploymentScript: deployment.deploymentScript,
        deployedOnBlock:
          deployment?.deployedOnBlock &&
          Number(BigInt(deployment.deployedOnBlock)),
      };
    }
  });

  return { contracts: allContracts, deployers };
}

function main() {
  const current_path_to_broadcast = join(__dirname, "..", "broadcast");
  const current_path_to_deployments = join(__dirname, "..", "deployments");

  const Deploymentchains = getFiles(current_path_to_deployments);
  const deployments = {};

  // Load existing deployments from deployments directory
  Deploymentchains.forEach((chain) => {
    if (!chain.endsWith(".json")) return;
    chain = chain.slice(0, -5);
    var deploymentObject = JSON.parse(
      readFileSync(`${current_path_to_deployments}/${chain}.json`)
    );
    deployments[chain] = deploymentObject;
  });

  // Process all deployments from all script folders
  const { contracts: allGeneratedContracts, deployers } = processAllDeployments(
    current_path_to_broadcast
  );

  // Handle UUPS proxies: the deployments JSON maps proxy addresses to
  // implementation contract names (e.g., { "0xProxy": "ContentToken" }).
  // We create entries using the proxy address + the implementation's ABI.
  // This is needed because the broadcast records proxies as "ERC1967Proxy"
  // (losing the implementation name), and deduplication collapses all
  // proxies into one entry.
  Object.entries(deployments).forEach(([chainId, chainDeployments]) => {
    if (typeof chainDeployments !== "object" || chainDeployments === null)
      return;

    Object.entries(chainDeployments).forEach(([address, contractName]) => {
      // Skip metadata entries like "networkName"
      if (!address.startsWith("0x")) return;

      const artifact = getArtifactOfContract(contractName);
      if (!artifact) return;

      if (!allGeneratedContracts[chainId]) {
        allGeneratedContracts[chainId] = {};
      }

      // Add/override: use the proxy address with the implementation's ABI
      allGeneratedContracts[chainId][contractName] = {
        address: address,
        abi: artifact.abi,
        inheritedFunctions: getInheritedFunctions(artifact),
      };
    });
  });

  const NEXTJS_TARGET_DIR = "../nextjs/contracts/";

  // Ensure target directories exist
  if (!existsSync(NEXTJS_TARGET_DIR)) {
    mkdirSync(NEXTJS_TARGET_DIR, { recursive: true });
  }

  // Generate the deployedContracts content
  const fileContent = Object.entries(allGeneratedContracts).reduce(
    (content, [chainId, chainConfig]) => {
      const cleanedChainConfig = Object.fromEntries(
        Object.entries(chainConfig).map(([contractName, contractData]) => {
          const { deploymentFile, deploymentScript, ...rest } = contractData;
          return [contractName, rest];
        })
      );
      return `${content}${parseInt(chainId).toFixed(0)}:${JSON.stringify(
        cleanedChainConfig,
        null,
        2
      )},`;
    },
    ""
  );

  // Write the files
  const fileTemplate = (importPath) => `
    ${generatedContractComment}
    import { GenericContractsDeclaration } from "${importPath}";

    const deployedContracts = {${fileContent}} as const;

    export default deployedContracts satisfies GenericContractsDeclaration;
  `;

  writeFileSync(
    `${NEXTJS_TARGET_DIR}deployedContracts.ts`,
    format(fileTemplate("~~/utils/scaffold-eth/contract"), {
      parser: "typescript",
    })
  );

  console.log(
    `📝 Updated TypeScript contract definition file on ${NEXTJS_TARGET_DIR}deployedContracts.ts`
  );

  // --- Auto-update scaffold.config.ts targetNetworks ---
  updateScaffoldConfig(Object.keys(allGeneratedContracts).map(Number));

  // --- Auto-update Ponder env with latest deployment for the selected target network ---
  updatePonderEnv(allGeneratedContracts, deployers);

  // --- Auto-update bot config.ts contract addresses ---
  updateBotConfig(allGeneratedContracts);
}

/**
 * Maps chain IDs to their viem/chains export names.
 * Add entries here when supporting new networks.
 */
const CHAIN_ID_TO_VIEM_NAME = {
  1: "mainnet",
  11155111: "sepolia",
  31337: "foundry",
  42161: "arbitrum",
  421614: "arbitrumSepolia",
  10: "optimism",
  11155420: "optimismSepolia",
  8453: "base",
  84532: "baseSepolia",
  42220: "celo",
  11142220: "celoSepolia",
  534351: "scrollSepolia",
  137: "polygon",
  80001: "polygonMumbai",
};

function updateScaffoldConfig(deployedChainIds) {
  const configPath = join(
    __dirname,
    "..",
    "..",
    "nextjs",
    "scaffold.config.ts"
  );
  if (!existsSync(configPath)) return;

  const content = readFileSync(configPath, "utf8");

  // Extract current targetNetworks entries
  const match = content.match(/targetNetworks:\s*\[([^\]]*)\]/);
  if (!match) return;

  const currentEntries = match[1]
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);

  // Build set of already-listed chain names
  const existingNames = new Set(
    currentEntries.map((e) => e.replace("chains.", ""))
  );

  // Add any deployed chains not yet listed
  let added = [];
  for (const chainId of deployedChainIds) {
    const viemName = CHAIN_ID_TO_VIEM_NAME[chainId];
    if (!viemName) {
      console.warn(
        `⚠️  No viem chain mapping for chain ID ${chainId} — add it to CHAIN_ID_TO_VIEM_NAME in generateTsAbis.js`
      );
      continue;
    }
    if (!existingNames.has(viemName)) {
      currentEntries.push(`chains.${viemName}`);
      existingNames.add(viemName);
      added.push(viemName);
    }
  }

  // Reorder: put the deploy target network first so the frontend defaults to it
  const deployTarget = process.env.DEPLOY_TARGET_NETWORK;
  const targetViemName =
    deployTarget === "localhost" ? "foundry" : deployTarget;
  let reordered = false;

  if (targetViemName) {
    const targetEntry = `chains.${targetViemName}`;
    const idx = currentEntries.indexOf(targetEntry);
    if (idx > 0) {
      currentEntries.splice(idx, 1);
      currentEntries.unshift(targetEntry);
      reordered = true;
    }
  }

  if (added.length === 0 && !reordered) return;

  const newTargetNetworks = `targetNetworks: [${currentEntries.join(", ")}]`;
  const updatedContent = content.replace(
    /targetNetworks:\s*\[([^\]]*)\]/,
    newTargetNetworks
  );
  writeFileSync(configPath, updatedContent);

  const changes = [];
  if (added.length > 0)
    changes.push(`added ${added.map((n) => `chains.${n}`).join(", ")}`);
  if (reordered)
    changes.push(`moved chains.${targetViemName} to first position`);
  console.log(
    `📝 Updated scaffold.config.ts targetNetworks: ${changes.join(", ")}`
  );
}

/**
 * Maps chain IDs to Ponder network names.
 * Must match the network keys in packages/ponder/ponder.config.ts.
 */
const CHAIN_ID_TO_PONDER_NETWORK = {
  11142220: "celoSepolia",
  31337: "hardhat",
  42220: "celo",
};

const DEPLOY_TARGET_TO_PONDER_NETWORK = {
  localhost: "hardhat",
  celoSepolia: "celoSepolia",
  celo: "celo",
};

const PONDER_NETWORK_TO_CHAIN_ID = {
  hardhat: 31337,
  celoSepolia: 11142220,
  celo: 42220,
};

const PONDER_RPC_DEFAULTS = {
  hardhat: "http://127.0.0.1:8545",
  celoSepolia: "https://forno.celo-sepolia.celo-testnet.org",
  celo: "https://forno.celo.org",
};

const PONDER_CONTRACT_ENV_KEYS = {
  ContentRegistry: "PONDER_CONTENT_REGISTRY_ADDRESS",
  RoundVotingEngine: "PONDER_ROUND_VOTING_ENGINE_ADDRESS",
  RoundRewardDistributor: "PONDER_ROUND_REWARD_DISTRIBUTOR_ADDRESS",
  CategoryRegistry: "PONDER_CATEGORY_REGISTRY_ADDRESS",
  ProfileRegistry: "PONDER_PROFILE_REGISTRY_ADDRESS",
  FrontendRegistry: "PONDER_FRONTEND_REGISTRY_ADDRESS",
  VoterIdNFT: "PONDER_VOTER_ID_NFT_ADDRESS",
  CuryoReputation: "PONDER_CREP_ADDRESS",
  HumanFaucet: "PONDER_HUMAN_FAUCET_ADDRESS",
  ParticipationPool: "PONDER_PARTICIPATION_POOL_ADDRESS",
  TimelockController: "PONDER_TIMELOCK_ADDRESS",
};

const PONDER_START_BLOCK_ENV_KEYS = {
  ContentRegistry: "PONDER_CONTENT_REGISTRY_START_BLOCK",
  RoundVotingEngine: "PONDER_ROUND_VOTING_ENGINE_START_BLOCK",
  RoundRewardDistributor: "PONDER_ROUND_REWARD_DISTRIBUTOR_START_BLOCK",
  CategoryRegistry: "PONDER_CATEGORY_REGISTRY_START_BLOCK",
  ProfileRegistry: "PONDER_PROFILE_REGISTRY_START_BLOCK",
  FrontendRegistry: "PONDER_FRONTEND_REGISTRY_START_BLOCK",
  VoterIdNFT: "PONDER_VOTER_ID_NFT_START_BLOCK",
  CuryoReputation: "PONDER_CREP_START_BLOCK",
  HumanFaucet: "PONDER_HUMAN_FAUCET_START_BLOCK",
  ParticipationPool: "PONDER_PARTICIPATION_POOL_START_BLOCK",
  TimelockController: "PONDER_TIMELOCK_START_BLOCK",
};

function parseEnvFile(content) {
  const env = {};
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx <= 0) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim();
    env[key] = value;
  }
  return env;
}

function serializeEnvFile(env) {
  const header = [
    "# Auto-generated by packages/foundry/scripts-js/generateTsAbis.js",
    "# Re-run `yarn deploy` to refresh these values.",
    "",
  ];

  const body = Object.keys(env)
    .sort()
    .map((key) => `${key}=${env[key]}`);

  return `${header.join("\n")}${body.join("\n")}\n`;
}

function updatePonderEnv(allGeneratedContracts, deployers = {}) {
  const deployTarget = process.env.DEPLOY_TARGET_NETWORK;
  const ponderNetwork = DEPLOY_TARGET_TO_PONDER_NETWORK[deployTarget];

  if (!ponderNetwork) {
    console.warn(
      `⚠️  Could not map DEPLOY_TARGET_NETWORK='${deployTarget}' to a Ponder network; skipping Ponder env sync.`
    );
    return;
  }

  const chainId = PONDER_NETWORK_TO_CHAIN_ID[ponderNetwork];
  const chainContracts = allGeneratedContracts[String(chainId)];
  if (!chainContracts) {
    console.warn(
      `⚠️  No generated contracts found for chainId ${chainId}; skipping Ponder env sync.`
    );
    return;
  }

  const ponderEnvPath = join(__dirname, "..", "..", "ponder", ".env.local");
  const existingEnv = existsSync(ponderEnvPath)
    ? parseEnvFile(readFileSync(ponderEnvPath, "utf8"))
    : {};

  // Respect explicit remote-network testing:
  // If deploying localhost while Ponder is pinned to a non-local network
  // (e.g. celoSepolia), do not rewrite .env.local to hardhat addresses.
  if (
    ponderNetwork === "hardhat" &&
    existingEnv.PONDER_NETWORK &&
    existingEnv.PONDER_NETWORK !== "hardhat"
  ) {
    console.log(
      `ℹ️  Skipping Ponder .env.local rewrite for localhost deploy because PONDER_NETWORK is pinned to ${existingEnv.PONDER_NETWORK}.`
    );
    return;
  }

  existingEnv.PONDER_NETWORK = ponderNetwork;

  const rpcEnvKey = `PONDER_RPC_URL_${chainId}`;
  if (!existingEnv[rpcEnvKey]) {
    existingEnv[rpcEnvKey] = PONDER_RPC_DEFAULTS[ponderNetwork];
  }

  const deployedBlocks = Object.values(chainContracts)
    .map((contract) => Number(contract?.deployedOnBlock || 0))
    .filter((blockNumber) => Number.isFinite(blockNumber) && blockNumber > 0);
  const chainStartBlock =
    deployedBlocks.length > 0 ? Math.min(...deployedBlocks) : 0;

  // Exclude deployer from token holder tracking (leaderboard)
  const deployerAddress = deployers[String(chainId)];
  if (deployerAddress) {
    existingEnv["PONDER_DEPLOYER_ADDRESS"] = deployerAddress;
  }

  const updatedContracts = [];
  for (const [contractName, addressEnvKey] of Object.entries(
    PONDER_CONTRACT_ENV_KEYS
  )) {
    const contractData = chainContracts[contractName];
    if (!contractData?.address) continue;

    existingEnv[addressEnvKey] = contractData.address;

    const blockEnvKey = PONDER_START_BLOCK_ENV_KEYS[contractName];
    const startBlock = Number(
      contractData.deployedOnBlock || chainStartBlock || 0
    );
    if (startBlock > 0) {
      existingEnv[blockEnvKey] = String(startBlock);
    }

    updatedContracts.push(contractName);
  }

  writeFileSync(ponderEnvPath, serializeEnvFile(existingEnv));
  console.log(
    `📝 Updated Ponder .env.local (${ponderNetwork}, chainId ${chainId}) with latest deployment addresses: ${updatedContracts.join(
      ", "
    )}`
  );
}

/**
 * Maps deployed contract names to the bot config.ts key names.
 */
const CONTRACT_TO_BOT_KEY = {
  CuryoReputation: "crepToken",
  ContentRegistry: "contentRegistry",
  RoundVotingEngine: "votingEngine",
  VoterIdNFT: "voterIdNFT",
  CategoryRegistry: "categoryRegistry",
};

function updateBotConfig(allGeneratedContracts) {
  const botConfigPath = join(__dirname, "..", "..", "bot", "src", "config.ts");
  if (!existsSync(botConfigPath)) return;

  let content = readFileSync(botConfigPath, "utf8");
  const updatedKeys = [];

  for (const [, contracts] of Object.entries(allGeneratedContracts)) {
    for (const [contractName, contractData] of Object.entries(contracts)) {
      const botKey = CONTRACT_TO_BOT_KEY[contractName];
      if (!botKey) continue;

      const regex = new RegExp(`(${botKey}:\\s*")0x[a-fA-F0-9]+(")`);
      const updated = content.replace(regex, `$1${contractData.address}$2`);
      if (updated !== content) {
        content = updated;
        updatedKeys.push(botKey);
      }
    }
  }

  if (updatedKeys.length > 0) {
    writeFileSync(botConfigPath, content);
    console.log(`📝 Updated bot contract addresses: ${updatedKeys.join(", ")}`);
  }
}

try {
  main();
} catch (error) {
  console.error("Error:", error);
  process.exitCode = 1;
}
